### ISSUE TITLE
Will a new rascaline install overwrite an existing equistore-core installation?

### ISSUE THREAD

**Issue by bananenpampe** [Luthaf/rascaline#197]
Recently there were some breaking equistore changes.
Since a rascaline install only installs the equistore-core packages, 
I would be interested if we could add some logic to the setup.py file that, if equistore-operations is already installed,
updates the latter as well.
Otherwise, the user might receive weird errors if equistore-core and operations are incompatible.

**Comment by Luthaf** [comment]
>  Will a new rascaline install overwrite an existing equistore-core installation?

yes, unfortunately

> I would be interested if we could add some logic to the setup.py file that, if equistore-operations is already installed,
updates the latter as well.

we can't do that, because rascaline will be built in a virtualenv by pip, containing only equistore-core, even if the use has equistore-operation installed elswhere.


----

The proper solution here is to release equistore-core on pypi, with a version number. Then both equistore-operations and rascaline can depend on the PyPI version, and equistore-operation and rascaline can check at runtime if they are using a compatible equistore-core version. 

The big remaining issue before we can release equistore-core to PyPI is finding a good name for it!

**Comment by Luthaf** [comment]
fixed by having metatensor on PyPI!
